### ISSUE TITLE
Map canvas issue.

### ISSUE THREAD

**Issue by kesaribharat** [lmotta/layertilesmapcanvas#1]
Hello sir, 
First of all great. Thanks to you for building such a nice tool. I wont say it as an issue but a feature that would help.

Right now the plugin is taking map canvas as default selected area if we have option to mask or select by layer in that case we can save lot of time and space. there are many blank tiles are coming in border areas.

**Comment by lmotta** [comment]
Thanks for your suggest.
I updated the plugin, I hope the new version can be adequate for you.
The new version do the downloads of only selected tiles, then, you can use selection tools or "Select by location" processing tool.

**Comment by kesaribharat** [comment]
Thanks a lot sir.

We have improved the plugin ourselves by adding a layer option.

Now the user can select a polygon layer and update the tiles.

We are working on selecting the nearest tile to the polygon. In a scenario
where we want all the tiles falling in a polygon a bounding box is a big
size to select

If we can select by the tile lying in the boundary then we can minimize the
no of tiles downloaded and will improve the extra overlapping.


please check our plugin very much your plugin we just tweaked it.
