### ISSUE TITLE
Feature request: Increase Zoom Level Range to 21

### ISSUE THREAD

**Issue by RCGIC** [lmotta/layertilesmapcanvas#3]
This tool works very well for imagery management and API testing, but it would be helpful if it supported to level 21 or 22 as many aerial and drone imagery projects create data with 3" or better GSD.

**Comment by lmotta** [comment]
Thanks RCGIC for your interest in my plugin.

I updated this plugin, at the moment the version is 1.4, where the range of zoom level (default) is 5 to 25.
If have a XYZ server layer  selected in legend when run the plugin, the zoom range is the same of server definition.

I hope this version is well for your work.

**Comment by RCGIC** [comment]
That works great thanks for doing this so quickly.
